import type { Metadata } from 'next';
import DefaultLayout from '@/components/layouts/DefaultLayout';

export const metadata: Metadata = {
  title: 'Home - Beestock',
  description: 'Generated by create next app',
};

export default function Layout({
                                 children,
                               }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <DefaultLayout>
      {children}
    </DefaultLayout>
  );
}
