import type { Metadata } from 'next';
import './globals.css';
import { Montserrat, Outfit } from 'next/font/google';
import ThemeProvider from '@/components/providers/ThemeProvider';

export const metadata: Metadata = {
  title: 'Beestock',
  description: 'Generated by create next app',
};

const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-outfit',
  display: 'swap',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-montserrat',
  display: 'swap',
});

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body
      className={`${outfit.variable} ${montserrat.variable} antialiased bg-gray-50 dark:bg-[#1C2128] text-zinc-900 dark:text-white`}
    >
    <ThemeProvider attribute="class"
                   defaultTheme="system"
                   enableSystem
                   disableTransitionOnChange>
      {children}
    </ThemeProvider>
    </body>
    </html>
  );
}
